languageCode = 'en-us'
baseURL = 'https://tp.esacteksab.com/'
title = 'tp'

[[menus.main]]

[params.Author]
github = 'esacteksab/tp'
name = 'esacteksab'

[build]
_merge = 'deep'

[markup]
_merge = 'deep'

[module]
[[module.imports]]
path = "github.com/esacteksab/simpl"
