languageCode = 'en-us'
baseURL      = 'https://tp.esacteksab.com/'
title        = 'tp'

[[menus.main]]


[Params]
  accentColor = 'blue'

[Params.Author]
  github = 'esacteksab/gh-tp'
  name   = 'esacteksab'

[build]
  _merge = 'deep'

[markup]
  _merge = 'deep'

[module]
  [[module.imports]]
    path = "github.com/esacteksab/simpl"
