languageCode = 'en-us'
baseURL = 'https://tp.esacteksab.com/'
title = 'tp'

[[menus.main]]

[markup.goldmark]
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true
title = true

[markup.highlight]
noClasses = false
wrapperClass = 'highlight not-prose'

[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 1


[params.Author]
github = 'esacteksab/tp'
name = 'esacteksab'


# required
# [build]
# [build.buildStats]
# enable = true
# [[build.cachebusters]]
# source = 'assets/notwatching/hugo_stats.json'
# target = 'css'
# [[build.cachebusters]]
# source = '(postcss|tailwind).config.js'
# target = 'css'
# [module]
# [[module.mounts]]
# source = 'assets'
# target = 'assets'
# [[module.mounts]]
# disableWatch = true
# source = 'hugo_stats.json'
# target = 'assets/notwatching/hugo_stats.json'
[[module.imports]]
path = "github.com/esacteksab/simpl"
