name: Labeler

on:
  pull_request:
    types:
      - opened

permissions:
  contents: read
  pull-requests: write

jobs:
  label-pr:
    uses: esacteksab/.github/.github/workflows/labeler.yml@3ee18be8891f7ce22f51dd63133bf512a616ffcc
