name: Labeler

on:
  pull_request:
    types:
      - opened

permissions:
  contents: read
  pull-requests: write

jobs:
  label-pr:
    uses: esacteksab/.github/.github/workflows/labeler.yml@4e572af21b05e3621a98caabda5df594e5bd93b8
