name: Pre-Commit

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  SKIP: ${{ vars.SKIP }}

permissions:
  contents: read

jobs:
  precommit-reusable:
    uses: esacteksab/.github/.github/workflows/pre-commit.yml@7d7d9f2d6f8782e0db28cb2c7b9dc7212cf18367
