name: Spell Check

permissions:
  contents: read

on: [pull_request]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

concurrency:
  group: "${{ github.workflow }}-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  typos-reusable:
    uses: esacteksab/.github/.github/workflows/spelling.yml@3a8f6743ec0c3bf58c1512ff4109952362e690f3
