name: Spell Check

permissions:
  contents: read

on: [pull_request]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

concurrency:
  group: "${{ github.workflow }}-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  typos-reusable:
    uses: esacteksab/.github/.github/workflows/spelling.yml@f2ba3f6b02af9b437a8224d8a6693421a1a65cca
